CREATE TABLE users (
	id INTEGER AUTO_INCREMENT NOT NULL,
	name VARCHAR(50) NOT NULL,
	password VARCHAR(50) NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE debts (
	id INTEGER AUTO_INCREMENT NOT NULL,
	amount INTEGER NOT NULL,
	description VARCHAR(200) NOT NULL,
	creditorid INTEGER NOT NULL,
	debtorid INTEGER NOT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY(creditorid) REFERENCES users(id),
	FOREIGN KEY(debtorid) REFERENCES users(id)
);

CREATE TABLE friends (
	id INTEGER AUTO_INCREMENT NOT NULL,
	friend1id INTEGER NOT NULL,
	friend2id INTEGER NOT NULL,
	confirmed BOOLEAN NOT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY(friend1id) REFERENCES users(id),
	FOREIGN KEY(friend2id) REFERENCES users(id)
);